[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.partitions = huge_app.csv

lib_ldf_mode = chain+

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DA2DP_I2S_AUDIOTOOLS=0
    -DA2DP_LEGACY_I2S_SUPPORT=1

lib_deps =
    https://github.com/pschatzmann/ESP32-A2DP.git
